### ISSUE TITLE
cli: shows stack traceback when .err file is not find

### ISSUE THREAD

**Issue by ankan17** [systemslab/popper#239]
When I do `popper run` with an invalid `validate.sh` file in a pipeline, the build fails and the following stack traceback is shown:

```
Executing mypipeline
setup.sh .
run.sh .
validate.sh .
Stage validate failed.
Logs for validate:.
Traceback (most recent call last):
  File "/home/ankan/Projects/popper-test/bin/popper", line 11, in <module>
    sys.exit(cli())
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/popper/commands/cmd_run.py", line 51, in cli
    time_out, skip)
  File "/home/ankan/Projects/popper-test/lib/python3.6/site-packages/popper/commands/cmd_run.py", line 97, in run_pipeline
    with open('popper_logs/{}{}'.format(stage, t), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'popper_logs/validate.err'
```

Is this the desired behavior?  Wouldn't we want to show a custom error message instead of showing the whole stack traceback?

**Comment by ankan17** [comment]
The above problem occurs because the code creates log files such as `validate.sh.err` but tries to open `validate.err`. A possible fix is:

```
 if ecode != 0:
    pu.info("Stage {} failed.".format(stage_file))
    STATUS = "FAIL"
    pu.info("Logs for {}:.".format(stage_file))
    for t in ['.err', '.out']:
        with open('popper_logs/{}{}'.format(stage_file, t), 'r') as f:
            pu.info(f.read())
            break
```

Instead of `stage`, `stage_file` should be used as shown above.

Should submit a PR regarding the same? @ivotron

**Comment by ivotron** [comment]
Good catch! I'll review your PR
