### ISSUE TITLE
cli: `popper workflow` breaks with Unicode characters

### ISSUE THREAD

**Issue by wtraylor** [systemslab/popper#486]
### Issue:
The `popper workflow <pipeline>` command fails if a script contains non-ASCII (Unicode) characters like e.g. ⇒’äöü.

### Steps to reproduce:
```bash
git init repo
cd repo
popper init
popper init myexp
# Add a non-ASCII character in a comment in pipelines/myexp/run.sh 
# (or any other script file)
popper workflow myexp
```

### Traceback output:
```
Traceback (most recent call last):
  File "/home/living/.local/bin/popper", line 10, in <module>
    sys.exit(cli())
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/popper/commands/cmd_workflow.py", line 197, in cli
    parser.parse(s)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/lark/lark.py", line 197, in parse
    return self.parser.parse(text)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/lark/parser_frontends.py", line 47, in parse
    return self.parser.parse(token_stream, self.lexer.set_parser_state)
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 69, in parse
    for i, token in enumerate(stream):
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/lark/lexer.py", line 248, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "/home/living/.virtualenv/popper/lib/python3.7/site-packages/lark/lexer.py", line 116, in lex
    raise UnexpectedInput(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column)
lark.lexer.UnexpectedInput: No token defined for: 'ä' in 'äöü\n\n' at line 2 col 25
```

**Comment by ivotron** [comment]
Hi, thanks a lot for reporting this @WolfgangTraylor . I'll look into it, but it's likely a limitation in the `lark` parser

**Comment by ivotron** [comment]
tested this with v2.x and it works OK
