### ISSUE TITLE
cli: add support for python 2.7

### ISSUE THREAD

**Issue by ivotron** [systemslab/popper#521]
Currently, we only support 3.7.x, so when `popper run` is executed on 2.7.x, the following error occurs:

```
Traceback (most recent call last):
  File "/usr/local/bin/popper", line 9, in <module>
    load_entry_point('popper==2.0.0.dev0', 'console_scripts', 'popper')()
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/popper-2.0.0.dev0-py2.7.egg/popper/commands/cmd_run.py", line 37, in cli
    pipeline.run(action)
  File "/usr/local/lib/python2.7/dist-packages/popper-2.0.0.dev0-py2.7.egg/popper/gha.py", line 196, in run
    self.run_stage(s)
  File "/usr/local/lib/python2.7/dist-packages/popper-2.0.0.dev0-py2.7.egg/popper/gha.py", line 201, in run_stage
    self.wf['action'][a]['runner'].run()
  File "/usr/local/lib/python2.7/dist-packages/popper-2.0.0.dev0-py2.7.egg/popper/gha.py", line 340, in run
    cmd[0] = os.path.join('./', cmd[0])
TypeError: 'unicode' object does not support item assignment
```

**Comment by barbaraDorame** [comment]
It looks like the problem is how the hcl library is composing the workflow, python3 is making 'runs' as a list of strings, and in python2 as a string. if you print cmd[0] in python2 it's 'i', if you print cmd it's 'init'. Might have to check why this happens in the hcl lib.

**Comment by ivotron** [comment]
hey @barbaraDorame! thanks a lot for looking into this. I think the root of this issue is [in this block](https://github.com/systemslab/popper/blob/751ba18/cli/popper/gha.py#L80-L91). The problem is that python 2.7 and 3.x have distinct ways of treating unicode strings. This is explained well [here](http://johnbachman.net/building-a-python-23-compatible-unicode-sandwich.html), in particular the "String type checking" section. We need a workaround that allows us to check if an attribute is a string in a way that is compatible for 2.7 and 3.
