### ISSUE TITLE
cli: errors in singularity engine due to race conditions

### ISSUE THREAD

**Issue by JayjeetAtGithub** [systemslab/popper#768]
This is how the error looks like [here](https://travis-ci.org/systemslab/popper/jobs/642387351?utm_medium=notification&utm_source=github_status).
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/popper", line 10, in <module>
    sys.exit(cli())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/popper/commands/cmd_run.py", line 171, in cli
    prepare_workflow_execution(**kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/popper/commands/cmd_run.py", line 209, in prepare_workflow_execution
    run_workflow(**kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/popper/commands/cmd_run.py", line 259, in run_workflow
    wf_runner.run(**kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/popper/gha.py", line 269, in run
    runtime, new_wf, s, reuse, parallel)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/popper/gha.py", line 296, in run_stage
    future.result()
  File "/opt/python/3.7.1/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/python/3.7.1/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/python/3.7.1/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/popper/gha.py", line 754, in run
    singularity_cache = SingularityRunner.setup_singularity_cache(self.wid)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/popper/gha.py", line 711, in setup_singularity_cache
    os.makedirs(singularity_cache)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/travis/.cache/.popper/singularity/b5a7c82838362d0281518262189f203e'
```

**Comment by JayjeetAtGithub** [comment]
Being addressed in #760
