### ISSUE TITLE
cli: "popper run" in "Getting Started" should test for Docker running

### ISSUE THREAD

**Issue by carlosmalt** [systemslab/popper#770]
Running `popper run` after `popper scaffold` produces an error if Docker isn't running. Yet "Getting Started" documentation does not mention that requirement. The error is a long stack trace that many people won't try to understand. Instead they might just give up.

1. Add Docker requirement to documentation
2. Describe what `popper run` is going to do (and what the long-running `[docker action] docker pull node:6` is trying to do)
3. Check whether Docker is running -- or at least print out a warning after the long error: "Make sure Docker is running!".

The error on MacOS 10.14.6 with HomeBrew-installed Python 3.7.6, `pip3 install virtualenv`, `pip install popper`, and `popper run --debug`:
```
(popper) bash-5.0$ popper run --debug
Found and running workflow at main.workflow
DEBUG: workflow:
!!python/object:popper.parser.Workflow
action:
  docker action:
    args:
    - node
    - --version
    name: docker action
    needs:
    - github official action
    next: !!set
      example action: null
    uses: docker://node:6
  example action:
    args:
    - github.com
    name: example action
    needs:
    - docker action
    uses: ./actions/example
  github official action:
    args:
    - ls
    name: github official action
    next: !!set
      docker action: null
    uses: popperized/bin/sh@master
name: example
'on': push
parsed_workflow:
  action:
    docker action:
      args:
      - node
      - --version
      name: docker action
      needs:
      - github official action
      next: !!set
        example action: null
      uses: docker://node:6
    example action:
      args:
      - github.com
      name: example action
      needs:
      - docker action
      uses: ./actions/example
    github official action:
      args:
      - ls
      name: github official action
      next: !!set
        docker action: null
      uses: popperized/bin/sh@master
  workflow:
    example:
      'on': push
      resolves: example action
props: {}
resolves:
- example action
root: !!set
  github official action: null
workflow_content:
- '

  '
- 'workflow "example" {

  '
- '  on = "push"

  '
- '  resolves = "example action"

  '
- '}

  '
- '

  '
- 'action "github official action" {

  '
- '  uses = "popperized/bin/sh@master"

  '
- '  args = ["ls"]

  '
- '}

  '
- '

  '
- 'action "docker action" {

  '
- '  needs = "github official action"

  '
- '  uses = "docker://node:6"

  '
- '  args = ["node", "--version"]

  '
- '}

  '
- '

  '
- 'action "example action" {

  '
- '  needs = "docker action"

  '
- '  uses = "./actions/example"

  '
- '  args = ["github.com"]

  '
- '}

  '
workflow_path: main.workflow
 
DEBUG: parse("popperized/bin/sh@master"): 
DEBUG:   service_url: https://github.com 
DEBUG:   service: github.com 
DEBUG:   user: popperized 
DEBUG:   repo: bin 
DEBUG:   action_dir: sh 
DEBUG:   version: master 
[popper] Cloning action repositories
[popper] - https://github.com/popperized/bin@master
DEBUG: parse("popperized/bin/sh@master"): 
DEBUG:   service_url: https://github.com 
DEBUG:   service: github.com 
DEBUG:   user: popperized 
DEBUG:   repo: bin 
DEBUG:   action_dir: sh 
DEBUG:   version: master 
Traceback (most recent call last):
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlosmalt/virtualenvs/popper/bin/popper", line 8, in <module>
    sys.exit(cli())
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/popper/commands/cmd_run.py", line 156, in cli
    prepare_workflow_execution(**kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/popper/commands/cmd_run.py", line 184, in prepare_workflow_execution
    run_workflow(**kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/popper/commands/cmd_run.py", line 226, in run_workflow
    wf_runner.run(**kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/popper/gha.py", line 193, in run
    WorkflowRunner.run_stage(new_wf, s, reuse, parallel)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/popper/gha.py", line 210, in run_stage
    wf.action[a]['runner'].run(reuse)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/popper/gha.py", line 373, in run
    if self.docker_exists():
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/popper/gha.py", line 407, in docker_exists
    all=True, filters={'name': self.cid})
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/docker/models/containers.py", line 937, in list
    since=since)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/docker/api/container.py", line 211, in containers
    res = self._result(self._get(u, params=params), True)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/carlosmalt/virtualenvs/popper/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
(popper) bash-5.0$
```

**Comment by ivotron** [comment]
thanks for reporting this Carlos. we'll address this and check for docker availability

**Comment by ivotron** [comment]
fixed in https://github.com/systemslab/popper/commit/2fc4e814517b16d844db5fa33e113f9c7825bacc
